### ISSUE TITLE
Cannot forward  or connect to the server

### ISSUE THREAD

**Issue by supun-kanda** [Stocard/node-ssh-forward#14]
```
var SSHConnection=require('node-ssh-forward').SSHConnection;
 
const sshConnection = new SSHConnection({
  endHost: 'ubuntu@publicIP,
  privateKey: 'keyPath'
})
await sshConnection.forward({
  fromPort: 5000,
  toPort: 5000,
  toHost: 'localhost'
})
```
I got this following error message
```
await sshConnection.forward({
^^^^^

SyntaxError: await is only valid in async function
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
```

**Comment by Junkern** [comment]
https://stackoverflow.com/questions/50518069/await-is-only-valid-in-async-function-when-using-mongoosejs-exec

`await` can only be used inside an `async` function. Your code should look like this:

```js
const SSHConnection = require('node-ssh-forward').SSHConnection;
 
const sshConnection = new SSHConnection({
  endHost: 'ubuntu@publicIP',
  privateKey: 'keyPath'
})

const run = async () => {
  await sshConnection.forward({
    fromPort: 5000,
    toPort: 5000,
    toHost: 'localhost'
  })
}
run()
```
